### Registration
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "name": "mmm",
    "email": "tto0@gmail.com",
    "password": "112233"
}

### Login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "example@gmail.com",
    "password": "112233"
}

### Logout
POST http://localhost:5000/auth/logout
Content-Type: application/json

{
  "token": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ODEsImVtYWlsIjoiZXhhbXBsZUBnbWFpbC5jb20iLCJpYXQiOjE3NjU0NjY0MTYsImV4cCI6MTc2ODA1ODQxNn0.T7nu9sng5C_2nqtdGzMAO_wBTitQQB-GbLloDPs3iuU"
}

### Get Access token by Refresh token
POST http://localhost:5000/auth/refresh
Content-Type: application/json

{
  "token": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ODEsImVtYWlsIjoiZXhhbXBsZUBnbWFpbC5jb20iLCJpYXQiOjE3NjU0NjYyMDMsImV4cCI6MTc2ODA1ODIwM30.C5JNu1be9rhLc2r44qT2B9nY1o7dfuSroiGuJ7MqYWg"

}