### Registration
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "name": "Md. Maruf Hossain",
    "email": "example@gmail.com",
    "password": "112233"
}

### Login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "example@gmail.com",
    "password": "112233"
}

### Logout
POST http://localhost:5000/auth/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsImVtYWlsIjoiZXhhbXBsZUBnbWFpbC5jb20iLCJpYXQiOjE3NjU0NTMzNTAsImV4cCI6MTc2ODA0NTM1MH0.q8W2mdR1RRx8-7pWw9qT5t3N_0mssPdY6_owLkyNruI"
}

### Get Access token by Refresh token
POST http://localhost:5000/auth/refresh
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsImVtYWlsIjoiZXhhbXBsZUBnbWFpbC5jb20iLCJpYXQiOjE3NjU0NTMzNTAsImV4cCI6MTc2ODA0NTM1MH0.q8W2mdR1RRx8-7pWw9qT5t3N_0mssPdY6_owLkyNruI"
}