### Get all ccsps
GET http://localhost:5000/ccsps
Content-Type: application/json

### Get a ccsp by code
GET http://localhost:5000/ccsps/5
Content-Type: application/json

### Create a ccsp
POST http://localhost:5000/ccsps
Content-Type: application/json

{
    "name": "CSE EVENING (4M)",
    "department": "19",
    "credits": 40,
    "terms": 8
}

### Update a ccsp by code
PUT http://localhost:5000/ccsps/5
Content-Type: application/json

{
    "name": "CSE EVENING (6M)"
}

### Delete a ccsp by code
DELETE http://localhost:5000/ccsps/8
Content-Type: application/json

### Get all the courses of a particular ccsp
GET http://localhost:5000/ccsps/2/courses
Content-Type: application/json

### Get a ccsp with the department info