### Get all ccsp
GET http://localhost:5000/ccsps
Content-Type: application/json

### Crate a ccsp
POST http://localhost:5000/ccsps
Content-Type: application/json

{
    "name": "CSE OBE (4M)",
    "departmentCode": "1010",
    "courses": ["OOP", "SQL"],
    "offeredTerm": [4, 5],
    "isOptional": [false, false],
    "credits": 40,
    "terms": 8
}
